"""empty message

Revision ID: 45e35476c4a2
Revises: 7a639a0bb1d7
Create Date: 2022-11-24 18:08:14.766143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e35476c4a2'
down_revision = '7a639a0bb1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateAbfahrt', sa.DateTime(), nullable=True),
    sa.Column('dateAnkunft', sa.DateTime(), nullable=True),
    sa.Column('von', sa.String(length=64), nullable=True),
    sa.Column('nach', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_nach'), ['nach'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_von'), ['von'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_von'))
        batch_op.drop_index(batch_op.f('ix_ticket_nach'))

    op.drop_table('ticket')
    # ### end Alembic commands ###
