"""empty message

Revision ID: c403b44beb4f
Revises: f0ccdca80d3e
Create Date: 2022-11-24 22:18:21.935259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c403b44beb4f'
down_revision = 'f0ccdca80d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('dateAbfahrt')
        batch_op.drop_column('dateAnkunft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateAnkunft', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('dateAbfahrt', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
