"""empty message

Revision ID: dc13be016285
Revises: 7b89a8fbb860
Create Date: 2022-12-26 16:23:11.172204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc13be016285'
down_revision = '7b89a8fbb860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startbahnhof', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('endbahnhof', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abschnitt', schema=None) as batch_op:
        batch_op.drop_column('endbahnhof')
        batch_op.drop_column('startbahnhof')

    # ### end Alembic commands ###
