"""empty message

Revision ID: f0ccdca80d3e
Revises: 45e35476c4a2
Create Date: 2022-11-24 22:15:36.781907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ccdca80d3e'
down_revision = '45e35476c4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preis', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ticket_preis'), ['preis'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_preis'))
        batch_op.drop_column('preis')

    # ### end Alembic commands ###
