"""empty message

Revision ID: 0726cfa7d8ac
Revises: 
Create Date: 2022-12-15 22:03:18.364710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0726cfa7d8ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fahrtstrecke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startPunkt', sa.String(), nullable=False),
    sa.Column('endPunkt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fahrtstrecke', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fahrtstrecke_endPunkt'), ['endPunkt'], unique=False)
        batch_op.create_index(batch_op.f('ix_fahrtstrecke_startPunkt'), ['startPunkt'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('vorname', sa.String(length=128), nullable=True),
    sa.Column('nachname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('abschnitt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startBahnhof', sa.String(length=20), nullable=False),
    sa.Column('endBahnhof', sa.String(length=20), nullable=False),
    sa.Column('nuetzungsentgelt', sa.Integer(), nullable=False),
    sa.Column('distanz', sa.Integer(), nullable=False),
    sa.Column('fahrtstrecke', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fahrtstrecke'], ['fahrtstrecke.id'], ),
    sa.PrimaryKeyConstraint('id', 'fahrtstrecke')
    )
    op.create_table('fahrtdurchführung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startDatum', sa.DateTime(), nullable=False),
    sa.Column('endDatum', sa.DateTime(), nullable=False),
    sa.Column('fahrtstrecke', sa.Integer(), nullable=True),
    sa.Column('preis', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fahrtstrecke'], ['fahrtstrecke.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fahrtdurchführung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fahrtdurchführung_endDatum'), ['endDatum'], unique=False)
        batch_op.create_index(batch_op.f('ix_fahrtdurchführung_fahrtstrecke'), ['fahrtstrecke'], unique=False)
        batch_op.create_index(batch_op.f('ix_fahrtdurchführung_startDatum'), ['startDatum'], unique=False)

    op.create_table('fahrtstrecke_abschnitte',
    sa.Column('fahrtstrecke', sa.Integer(), nullable=False),
    sa.Column('abschnitt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abschnitt'], ['abschnitt.id'], ),
    sa.ForeignKeyConstraint(['fahrtstrecke'], ['fahrtstrecke.id'], ),
    sa.PrimaryKeyConstraint('fahrtstrecke', 'abschnitt')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('startStation', sa.String(), nullable=True),
    sa.Column('endStation', sa.String(), nullable=True),
    sa.Column('fahrtdurchführung', sa.Integer(), nullable=True),
    sa.Column('preis', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fahrtdurchführung'], ['fahrtdurchführung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_endStation'), ['endStation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_startStation'), ['startStation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_userid'), ['userid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_userid'))
        batch_op.drop_index(batch_op.f('ix_ticket_startStation'))
        batch_op.drop_index(batch_op.f('ix_ticket_endStation'))

    op.drop_table('ticket')
    op.drop_table('fahrtstrecke_abschnitte')
    with op.batch_alter_table('fahrtdurchführung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fahrtdurchführung_startDatum'))
        batch_op.drop_index(batch_op.f('ix_fahrtdurchführung_fahrtstrecke'))
        batch_op.drop_index(batch_op.f('ix_fahrtdurchführung_endDatum'))

    op.drop_table('fahrtdurchführung')
    op.drop_table('abschnitt')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('fahrtstrecke', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fahrtstrecke_startPunkt'))
        batch_op.drop_index(batch_op.f('ix_fahrtstrecke_endPunkt'))

    op.drop_table('fahrtstrecke')
    # ### end Alembic commands ###
