"""empty message

Revision ID: 16fc169a3346
Revises: 00561ac921a0
Create Date: 2023-01-18 16:35:52.986727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fc169a3346'
down_revision = '00561ac921a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generelle_aktion')
    op.drop_table('fahrtstrecke_aktion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fahrtstrecke_aktion',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('prozent', sa.REAL(), nullable=False),
    sa.Column('startDatum', sa.TEXT(), nullable=False),
    sa.Column('endDatum', sa.TEXT(), nullable=False),
    sa.Column('fahrtstrecke', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generelle_aktion',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('prozent', sa.REAL(), nullable=False),
    sa.Column('startDatum', sa.TEXT(), nullable=False),
    sa.Column('endDatum', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
