"""empty message

Revision ID: 650a6ffe08ca
Revises: 400ed946a245
Create Date: 2023-01-02 13:22:54.863476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650a6ffe08ca'
down_revision = '400ed946a245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fahrtdurchführung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('richtung', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fahrtdurchführung', schema=None) as batch_op:
        batch_op.drop_column('richtung')

    # ### end Alembic commands ###
