"""empty message

Revision ID: 7a639a0bb1d7
Revises: 0a747b040430
Create Date: 2022-11-24 15:14:59.474365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a639a0bb1d7'
down_revision = '0a747b040430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vorname', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('nachname', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nachname')
        batch_op.drop_column('vorname')

    # ### end Alembic commands ###
